name: Sync to Glitch Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full clone to avoid shallow update error

      - name: Push to Glitch
        env:
          GLITCH_STAGING_URL: ${{ secrets.GLITCH_STAGING_URL }}
        run: |
          git remote add glitch $GLITCH_STAGING_URL
          git push glitch staging:main --force