name: Sync to Glitch

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full clone to avoid shallow update error

      - name: Push to Glitch
        env:
          GLITCH_URL: ${{ secrets.GLITCH_URL }}
        run: |
          git remote add glitch $GLITCH_URL
          git push glitch beta:main --force